```scala
Welcome to Scala version 2.8.0.Beta1-RC6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_17).

scala> List(1) match { case Seq(x) => x } 
res1: Int = 1

scala> Array(1) match { case Seq(x) => x }
scala.MatchError: [I@76186a96
	at .<init>(<console>:5)
	at .<clinit>(<console>)
	at RequestResult$$.<init>(<console>:4)
	at RequestResult$$.<clinit>(<console>)
	at RequestResult$$scala_repl_result(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at scala.tools.nsc.Interpreter$$Request$$$$anonfun$$loadAndRun$$1$$$$anonfun$$apply$$13.apply(Interpreter.scala:798)
```

works fine in 2.7:
```scala
Welcome to Scala version 2.7.7.final (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_17).

scala> Array(1) match { case Seq(x) => x }
res3: Int = 1
```
