When migrating from scala 2.7.7 to 2.8.0.Beta1 I've encountered runtime error when in mapping Array to functions with repeated parameters. Following reduced testcase:
```scala
object Test {
  def main(args: Array[String]) {
    args.map(_ => foo _) // java.lang.ClassNotFoundException: scala.<repeated>
    // args.toList.map(_ => foo _) // this works
  }

  def foo(xs: String*) {}
}
```

produces this error:
```scala
Exception in thread "main" java.lang.NoClassDefFoundError: scala/<repeated>
	at Test$$.main(Test.scala:3)
	at Test.main(Test.scala)
Caused by: java.lang.ClassNotFoundException: scala.<repeated>
	at java.net.URLClassLoader$$1.run(URLClassLoader.java:200)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:315)
	at sun.misc.Launcher$$AppClassLoader.loadClass(Launcher.java:330)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:250)
	at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:398)
	... 2 more
```
