I'm not sure if this even a bug, or just a feature. However:

This code will throw StackOverflowError 
{noformat}
var filtered  = Map("1" -> 2)
for(i <- 1 to 10000) {
  filtered = filtered.filterKeys(s => s != "2")
}
println(filtered.get("1"))
{noformat}

This would not:
{noformat}
 var filtered  = Map("1" -> 2)
 val add = Map("2" -> 1)
 for(i <- 1 to 10000) {
    filtered = filtered.filterKeys(_ != "2") ++ add
 }
println(filtered.get("1"))
{noformat}

This will throw as well:

{noformat}
var filtered  = Map("1" -> 2)
val add = Map()
for(i <- 1 to 10000) {
  filtered = filtered.filterKeys(_ != "2") ++ add
}
println(filtered.get("1"))
{noformat}
