(In r23742) Finally figured out what needed to happen for

  import scala.`package`.Throwable

not to break the repl.  Closes scala/bug#3673, no review.
