```scala
sbendiola@steve-bendiolas-computer /tmp $$ scalac -version  
Scala compiler version 2.7.2.RC2 -- Copyright 2002-2008, LAMP/EPFL
sbendiola@steve-bendiolas-computer /tmp $$ scalac Bug.scala 
sbendiola@steve-bendiolas-computer /tmp $$ scala -version
Scala code runner version 2.7.2.RC2 -- Copyright 2002-2008, LAMP/EPFL
sbendiola@steve-bendiolas-computer /tmp $$ scala example.Bug
java.lang.ExceptionInInitializerError
        at example.Bug$$.<init>(Bug.scala:32)
        at example.Bug$$.<clinit>(Bug.scala)
        at example.Bug.main(Bug.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:585)
        at scala.tools.nsc.ObjectRunner$$$$anonfun$$run$$1.apply(ObjectRunner.scala:75)
        at scala.tools.nsc.ObjectRunner$$.withContextClassLoader(ObjectRunner.scala:49)
        at scala.tools.nsc.ObjectRunner$$.run(ObjectRunner.scala:74)
        at scala.tools.nsc.MainGenericRunner$$.main(MainGenericRunner.scala:164)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
Caused by: java.lang.ClassCastException: example.Bug$$SimpleService
        at example.Bug$$TestContext$$.service_$$eq(Bug.scala:17)
        at example.Bug$$Contexts$$class.$$init$$(Bug.scala:14)
        at example.Bug$$TestContext$$.<init>(Bug.scala:17)
        at example.Bug$$TestContext$$.<clinit>(Bug.scala)
        ... 12 more

```
Notably, the exception goes away if you change line 18
```scala
override val service = new TestService
```
to
```scala
override val service : Service = new TestService
```
Furthermore, I was under the impression that for val overrides that the code for a particular val in a parent should not be executed if it has been overridden.  However, it seems that there must be a corner case for traits because if Contexts is changed from a trait to a class the exception also does not occur.
This looks to be fixed in trunk, so I am closing.
```scala
[paulp@jon 1407 (master)]$$ scala example.Bug
example.Bug$$TestContext$$@db9f45
```
